### ISSUE TITLE
DjlImageClassifierFactory should not return null if importPath isn't given as an input

### ISSUE THREAD

**Issue by deki** [frankfliu/visrec-djl#2]
I tried to run https://github.com/JavaVisRec/jsr381-examples/blob/master/src/main/java/jsr381/example/CatDogRecognition.java using DJL by replacing javax.visrec:visrec-ri with ai.djl.jsr381:jsr381. While the example works fine with the RI, a NPE occurs with DJL. Reason for that is that DjlImageClassifierFactory returns null when importPath is not given as an input. When I compare DjlImageClassifierFactory with javax.visrec.ri.spi.BufferedImageClassifierFactory it looks the current implementation is incomplete.

**Comment by frankfliu** [comment]
I just added training part to SimpleImageClassifier: https://github.com/JavaVisRec/visrec-djl/pull/5

**Comment by deki** [comment]
Great, thanks a lot!
